<?php namespace Nord\Lumen\Elasticsearch\Search\Aggregation\Metrics;

/**
 * A single-value metrics aggregation that keeps track and returns the minimum value among numeric values extracted from
 * the aggregated documents. These values can be extracted either from specific numeric fields in the documents, or be
 * generated by a provided script.
 *
 * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-min-aggregation.html
 */
class MinAggregation extends AbstractAggregation
{
    /**
     * @inheritdoc
     */
    public function toArray()
    {
        return [
            'min' => [
                'field' => $this->getField()
            ]
        ];
    }
}
