<?php namespace Nord\Lumen\Elasticsearch\Search\Aggregation\Metrics;

/**
 * A single-value metrics aggregation that keeps track and returns the minimum value among numeric values extracted from
 * the aggregated documents. These values can be extracted either from specific numeric fields in the documents, or be
 * generated by a provided script.
 *
 * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-min-aggregation.html
 */
class MinAggregation extends AbstractAggregation
{
    /**
     * @var string
     */
    private $field;


    /**
     * @inheritdoc
     */
    public function toArray()
    {
        return [
            'min' => [
                'field' => $this->getField()
            ]
        ];
    }


    /**
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }


    /**
     * @param string $field
     * @return MinAggregation
     */
    public function setField($field)
    {
        $this->field = $field;
        return $this;
    }
}
